### PR TITLE
  (#1618): Add DisplayNativeAmd enum variant to ColorSpaceEnum

### LINKED ISSUE #1618: Wrong Value for Color Space Enum error occurs when underlying device provides a surface format that utilizes the VK_COLOR_SPACE_DISPLAY_NATIVE_AMD color space
*   Version of vulkano: 0.23.0  and 0.24.0
*   OS: Windows 10 Pro
*   GPU (the selected PhysicalDevice): AMD Radeon RX 580
*   GPU Driver:  2.0.179

# Sample Code Demonstrating issue
 
```
 use std::sync::Arc;
use vulkano::device::Device;
use vulkano::device::Queue;
use vulkano::instance::Instance;
use vulkano::instance::PhysicalDevice;
use vulkano::Version;
use winit::event_loop::EventLoop;
use winit::window::WindowBuilder;

fn main() {
    let mut extensions = vulkano_win::required_extensions();

    extensions.ext_swapchain_colorspace = true;
    extensions.khr_device_group_creation = true;

    let instance = Instance::new(
        None,
        Version::V1_2,
        &vulkano::instance::InstanceExtensions::supported_by_core().unwrap(),
        None,
    )
    .expect("failed to create vulkan instance");

    let physical_device = PhysicalDevice::enumerate(&instance)
        .next()
        .expect("failed to retrieve physical device");

    let device_id = physical_device.properties().device_name.as_ref().unwrap();

    let queue_family = physical_device
        .queue_families()
        .find(|&q| q.supports_graphics())
        .expect("Could not find a queue family supporting graphics");

    let device_extensions = vulkano::device::DeviceExtensions {
        khr_swapchain: true,
        ..vulkano::device::DeviceExtensions::supported_by_device(physical_device.clone())
    };

    let (device, mut queues) = Device::new(
        physical_device,
        physical_device.supported_features(),
        &device_extensions,
        [(queue_family, 0.5)].iter().cloned(),
    )
    .expect("Failed to create device");

    let queue = queues.next().unwrap();

    draw_to_a_window(
        device.clone(),
        queue.clone(),
        instance.clone(),
        physical_device.clone(),
    );
}

fn draw_to_a_window(
    device: Arc<Device>,
    queue: Arc<Queue>,
    vulkan_instance: Arc<Instance>,
    physical: PhysicalDevice,
) {
    let event_loop = EventLoop::new();
    let surface = WindowBuilder::new().build(&event_loop).unwrap();

    let vk_surface =
        vulkano_win::create_vk_surface_from_handle(surface, vulkan_instance.clone()).unwrap();

    println!("Attempting to get surface capabilities");

    let wrappedCaps = vk_surface.capabilities(physical.clone());
}

 ```
# Issue

When attempting to retrieve the surface capabilites of a physical device via

```vk_surface.capabilities( physical.clone( ) )```

The following error occurs:
```
thread 'main' panicked at 'Wrong value for color space enum', C:\Users\kdela\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.24.0\src\swapchain\capabilities.rs:655:18
```
Seems to be due to AMD Radeon RX 580 having the VK_COLOR_SPACE_DISPLAY_NATIVE_AMD color space as the color space in one of it's potential surface formats. Adding a new ColorSpace enum variant to cover this color space seems to fix the issue (I went ahead and cloned the repo, and added it myself to see [ ash already exposes this value as part of it's ColorSpaceKHR struct]. Seems to have done the job, but I have no means done any robust testing)

### PR DESCRIPTION
**Pull request by kdelamo94**
Fixes #1618 where GPUs that support VK_COLOR_SPACE_DISPLAY_NATIVE_AMD ( one specific example being the AMD Radeon Rx 580 Series ) in its surface format color spaces would cause Vulkano to Panic when checking the surface capabilities of the device

Fixed by adding a new enum variant to the ColorSpace enum that covers that color space. Ash already provides a value in their ColorSpaceKHR struct for this color space.

### CODE REVIEW

File: vulkano/src/swapchain/capabilities.rs [hunk 1]
```diff
@@ -625,6 +625,7 @@ pub enum ColorSpace {
     AdobeRgbLinear = ash::vk::ColorSpaceKHR::ADOBERGB_LINEAR_EXT.as_raw(),
     AdobeRgbNonLinear = ash::vk::ColorSpaceKHR::ADOBERGB_NONLINEAR_EXT.as_raw(),
     PassThrough = ash::vk::ColorSpaceKHR::PASS_THROUGH_EXT.as_raw(),
+    DisplayNativeAmd = ash::vk::ColorSpaceKHR::DISPLAY_NATIVE_AMD.as_raw()
```
Comment (Rua) [inline vulkano/src/swapchain/capabilities.rs:628]: Vulkano doesn't add vendor suffixes to its names, as you can see above your code where the `Ext` suffix is not present on the enum variants. Could you remove the `Amd` suffix?

**Comment by Rua** [comment]
Thank you for your PR! Just so you know, if you type `fixes #1618` in your first post somewhere, it automatically ties this PR to your previous issue so they will both be closed when this PR is merged.

File: vulkano/src/swapchain/capabilities.rs (hunk 1 above)
Comment (kdelamo94) [reply vulkano/src/swapchain/capabilities.rs:628]: Ahh, I see. Of course. I'll remove it now. Thanks for informing me.

**Comment by Eliah-Lakhin** [comment]
@kdelamo94 Thank you for your contribution!

And thanks to @Rua for your help in review!

PR is merged. :+1:
